late double height, width;

const double defPadding = 12;

const apiKey = "82230d50b1c5444fb0d83023240112";

const weatherImages = {
  'Partly cloudy': 'assets/images/weather/partlyCloudy.png',
  'Partly Cloudy ': 'assets/images/weather/partlyCloudy.png',
  'Partly Cloudy': 'assets/images/weather/partlyCloudy.png',
  'Moderate rain': 'assets/images/weather/moderateRain.png',
  'Moderate Rain ': 'assets/images/weather/moderateRain.png',
  'Patchy rain possible': 'assets/images/weather/moderateRain.png',
  'Patchy rain possible ': 'assets/images/weather/moderateRain.png',
  'Patchy rain nearby': 'assets/images/weather/moderateRain.png',
  'Patchy rain nearby ': 'assets/images/weather/moderateRain.png',
  'Patchy moderate snow': 'assets/images/weather/snow.png',
  'Patchy moderate snow ': 'assets/images/weather/snow.png',
  'Light snow': 'assets/images/weather/snow.png',
  'Moderate snow': 'assets/images/weather/snow.png',
  'Heavy snow': 'assets/images/weather/snow.png',
  'Blowing snow': 'assets/images/weather/snow.png',
  'Sunny': 'assets/images/weather/sun.png',
  'Sunny ': 'assets/images/weather/sun.png',
  'Clear': 'assets/images/weather/sun.png',
  'Clear ': 'assets/images/weather/sun.png',
  'Overcast': 'assets/images/weather/cloud.png',
  'Overcast ': 'assets/images/weather/cloud.png',
  'Cloudy': 'assets/images/weather/cloud.png',
  'Fog ': 'assets/images/weather/cloud.png',
  'Fog': 'assets/images/weather/cloud.png',
  'Light rain': 'assets/images/weather/moderateRain.png',
  'Light Rain ': 'assets/images/weather/moderateRain.png',
  'Moderate rain at times': 'assets/images/weather/moderateRain.png',
  'Moderate rain at times ': 'assets/images/weather/moderateRain.png',
  'Heavy rain': 'assets/images/weather/heavyRain.png',
  'Heavy Rain': 'assets/images/weather/heavyRain.png',
  'Heavy rain at times': 'assets/images/weather/heavyRain.png',
  'Heavy rain at times ': 'assets/images/weather/heavyRain.png',
  'Light freezing rain': 'assets/images/weather/heavyRain.png',
  'Light freezing rain ': 'assets/images/weather/heavyRain.png',
  'Moderate or heavy snow showers': 'assets/images/weather/snow.png',
  'Moderate or heavy freezing rain': 'assets/images/weather/heavyRain.png',
  'Moderate or heavy freezing rain ': 'assets/images/weather/heavyRain.png',
  'Moderate or heavy rain shower': 'assets/images/weather/heavyRain.png',
  'Moderate or heavy rain shower ': 'assets/images/weather/heavyRain.png',
  'Moderate or heavy rain with thunder': 'assets/images/weather/heavyRain.png',
  'Moderate or heavy rain with thunder ': 'assets/images/weather/heavyRain.png',
  'Light sleet': 'assets/images/weather/sleet.png',
  'Light Sleet': 'assets/images/weather/sleet.png',
  'Light Sleet ': 'assets/images/weather/sleet.png',
  'Moderate sleet': 'assets/images/weather/sleet.png',
  'Moderate Sleet': 'assets/images/weather/sleet.png',
  'Heavy sleet': 'assets/images/weather/sleet.png',
  'Heavy Sleet': 'assets/images/weather/sleet.png',
  'Mist': 'assets/images/weather/partlyCloudy.png',
  'other': 'assets/images/weather/moderateRain.png',
};
